# Generated by Django 6.0.4 on 2026-04-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postview',
            name='viewer_ip',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
